### ISSUE TITLE
[Mod Incompatibility] Incompatible with Dead Totems

### ISSUE THREAD

**Issue by ConqAra** [TheIllusiveC4/CurioOfUndying#16]
### Minecraft Version

1.18.2

### What happened?

Hello I made a 1.18.2 port for [Dead Totems](https://github.com/dzwdz/deadtotems/pull/2) (i am not a mod dev) and I've noticed when having the totem of undying in the charm slot and upon using it, a dead totem will not spawn. 

I was wondering what would be a quick fix to this.

### How do you trigger this bug?

1. Have dead totems installed
2. Die with the totem of undying in your trinket charm slot
3. Totem of undying is removed and the Dead totem doesn't appear when it's suppose to.

### Loader

Fabric

### Loader Version

0.14.10

### Mod Version

trinketofundying-fabric-2.0.2-1.18.2

**Comment by TheIllusiveC4** [comment]
There's no real quick fix for something like this, because the integration would need to be directly coded into either Dead Totems or this mod. And you could only do it from Dead Totems if I offered some kind of API in this mod to do so, which is possible but I'm not sure is the proper solution.

I think it makes the most sense for me to code the integration into this mod as I did back in 1.16.5. However, it seems that your port has not yet been accepted by the mod developer so we would need to revisit this discussion once a new build of Dead Totems has actually been released that I can base the integration on.
