### ISSUE TITLE
[Bug]: Quilt Crash On Startup

### ISSUE THREAD

**Issue by PixelQubed** [TheIllusiveC4/CurioOfUndying#26]
### Minecraft Version

1.20.1

### What happened?

Crashes on startup. 
I don't have any more info than that other than the fabric version loads fine on Quilt and the Quilt-specific version on Modrith doesn't load and runs into this error.

### How do you trigger this bug?

1. Installed the latest version of the mod.
2. Launched the Minecraft Quilt Instance
3. Error Occurs.

### Loader

Quilt

### Loader Version

Quilt 0.19.1

### API Version

Quilted Fabric API (QFAPI) 7.0.4 / Quilt Standard Libraries (QSL) 6.0.3

### Mod Version

Charm Of Undying-Quilt 6.4.2+1.20.1

### Relevant Log Outputs

https://mclo.gs/hNZlgVB

**Comment by TheIllusiveC4** [comment]
This is because you have a version of Vein Mining installed that is for Fabric and not Quilt. It's a niche error, basically the library that all my mods use are embedded into each of them. However, the Fabric and Quilt versions of the library are not compatible with each other (because they don't expect to be loaded in the same environment).

I think you can fix the crash simply by installing the Quilt version of Vein Mining instead.

**Comment by PixelQubed** [comment]
Yep, you were right. I'm sorry for not spotting that.

**Comment by TheIllusiveC4** [comment]
It's alright, this is actually good for me to know because I didn't realize this might be an issue. I'll have to see if I can make them cross-compatible at some point to avoid this.
